# Generated by Django 4.2.6 on 2023-10-13 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0002_alter_question_options_rename_titla_question_title"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Question",
        ),
    ]
